FROM bmbroom/ngchmmanagerdefault:latest

MAINTAINER Bradley Broom <bmbroom@mdanderson.org>

ADD chmManagerConfig /chmManagerConfig

# Temporary fix for permissions issue when running on Google cloud but not locally
USER 0
